#
# Makefile
#

build:
	@echo "Compiling pngdefry"
	@gcc pngdefry.c -o pngdefry
	@echo "pngdefry compiled!"

all: build

install: build
	@echo "Comying pngdefry"
	@mv pngdefry /bin/
	@echo "pngdefrycopied!"
